<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Welcome to iDiscuss - Coding Forums</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
</head>

<body>
    <?php
    include 'partials/_dbconnect.php';
    include 'partials/_header.php';
    ?>

    <div class="container">
        <h1>About</h1>
        <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Tempore accusantium cum id ipsa fuga, quisquam consectetur quos, saepe dicta soluta illum repellat repudiandae, dolore dolores aut. Architecto molestias sint eligendi dolore ut facere doloremque dolorum ab, quos quaerat eius? Laboriosam deleniti dolorem omnis aliquid atque accusantium laborum accusamus vel explicabo, obcaecati illo quidem delectus ipsam ut eveniet, rerum dignissimos porro voluptatibus alias facilis! Voluptatem eaque deleniti, eos voluptatibus debitis fugit veritatis nobis soluta corporis, velit error. Aliquid quidem vel, laudantium eum nemo iste adipisci at exercitationem pariatur! Laudantium vitae iusto earum nesciunt vero quasi modi est asperiores? Minima id modi facere velit rem amet quisquam a, quasi officia. Voluptas ut, omnis rerum soluta dicta numquam, libero eius quia velit repellendus at nisi! Eos ratione perferendis mollitia, cupiditate quam assumenda ut culpa iste provident nisi possimus impedit porro odit! Tempora nisi assumenda officia laborum odio delectus sint a hic reiciendis, magnam, nostrum quaerat vero consequuntur voluptate. Sapiente, assumenda iure error ex dolore omnis. Laboriosam, in. Molestias animi harum minus, assumenda officiis excepturi eum accusamus magnam dicta dolore placeat ad sapiente earum facilis unde debitis perspiciatis mollitia pariatur corrupti sint necessitatibus, doloribus provident iusto eos? Consequuntur aspernatur eveniet repudiandae odit, inventore fugiat doloribus veniam quas voluptatum? Ratione similique corporis ut atque iure
        </p>
        <p>magnam vitae, reiciendis omnis inventore eius aperiam rerum, praesentium exercitationem, nulla odio assumenda dolorum sequi magni alias id ipsam perferendis? Consequuntur, repudiandae in nulla facere ea eius quae quod id est laboriosam, impedit accusamus! Deleniti expedita perferendis cum eveniet, porro impedit quaerat iusto. Labore ratione quas reprehenderit porro modi nesciunt, necessitatibus nemo architecto, optio possimus dolorum! Delectus vero veniam ad quae officiis deleniti similique recusandae, culpa quis eos veritatis reprehenderit! Exercitationem dolorum qui ullam dolores vel assumenda eveniet, quasi velit veritatis. Quis possimus nostrum beatae error earum corrupti nemo consectetur at? Nemo voluptatibus perferendis accusamus optio aliquid fuga quae dolorem? Explicabo vero iusto voluptatibus veritatis deserunt perferendis, a sit necessitatibus laboriosam consectetur, dolorem ut quo placeat praesentium consequuntur numquam. Aspernatur nesciunt, assumenda blanditiis inventore voluptatum quo quas rerum libero maiores delectus, ut corporis rem saepe accusantium. Incidunt itaque impedit similique totam a libero consequatur beatae doloribus harum, rerum officia commodi iure quaerat? Dolorem facere fuga, placeat voluptatem dignissimos, cupiditate temporibus ab eos optio inventore eligendi, quasi amet tempora quam atque necessitatibus harum voluptates libero facilis beatae ipsam. Ut omnis similique voluptate nihil iste id libero magnam hic necessitatibus, tempora esse qui at! Aliquam odit saepe aspernatur ipsa, dolorem ut obcaecati temporibus mollitia error maxime, repellat odio dolore, nulla quia placeat pariatur alias. Natus incidunt consequatur, exercitationem a veritatis nobis accusantium repellendus dolorem maiores. Repellendus molestias veniam tempore omnis consequuntur amet deserunt repellat qui explicabo fuga? Inventore hic modi error fuga repellat sunt, itaque, numquam sequi doloremque maxime beatae cum nostrum asperiores. Voluptatibus unde iste tempora et minima, dolores vitae dolor aliquam ab amet fuga illum aut omnis neque id. Nisi nihil beatae, accusamus dolore debitis adipisci! Cumque maxime delectus accusamus, fugiat architecto facere magnam, iusto beatae sapiente, excepturi consequatur voluptas?
        </p>
        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam autem quam ipsam fugiat, quasi vero voluptate incidunt reprehenderit necessitatibus quos asperiores id a nulla modi distinctio et rem nostrum. Ea quae nobis non, libero magni reiciendis facere molestiae labore porro temporibus, sint vel, quam debitis nam. Quaerat sint incidunt quidem. Illo sapiente earum, esse tempore vero rerum error eum incidunt consequatur veritatis, aperiam sequi in, quia omnis? Perspiciatis quis aspernatur aperiam. Odit, dolor eligendi doloribus soluta rerum asperiores officia optio laborum minus quo ex fugiat animi. Repellat esse libero molestias, amet quisquam vel, praesentium nihil voluptatum ratione delectus, rem eos eligendi quas voluptates optio. Quidem, assumenda. Doloribus totam placeat labore aspernatur alias deleniti aliquam error laudantium consectetur explicabo nesciunt voluptates similique fugit vel tempora inventore provident sint illo, officiis quaerat ex cumque quae? Illum, aliquam. Eius maxime nobis facilis, tenetur quas cum provident. Nostrum ratione iure repudiandae, distinctio voluptas blanditiis? Quae dolor porro esse alias quos placeat doloremque dicta! Nam, impedit. Dignissimos aliquid esse saepe, inventore, voluptate sunt enim odio hic ab et dolor quaerat delectus vitae ratione velit consectetur suscipit sit perferendis rerum culpa! Qui rem reprehenderit voluptatem esse, exercitationem dicta fugiat quaerat, quidem sed pariatur, quas saepe voluptates quasi assumenda provident consequuntur neque iste dignissimos accusamus autem. Accusamus quidem architecto nihil dicta eum, placeat incidunt reiciendis tempora nam obcaecati officia iure voluptate neque id ex culpa. Adipisci iusto, eaque odit ab amet fugit asperiores consequuntur delectus, est rem porro ipsam debitis necessitatibus aspernatur dolorem dignissimos earum! Ipsam, molestias provident. Rem perferendis maxime, quas est commodi autem hic magnam eveniet minus ad, vel eum quisquam suscipit possimus. Vero, odit nesciunt harum perspiciatis animi voluptatum rerum incidunt quos veniam sapiente reiciendis. Sapiente ducimus veniam dignissimos minus, et beatae. Asperiores totam laboriosam harum, ab ipsa eveniet impedit minima repellat exercitationem nam.
        </p>
    </div>
    <?php
    include 'partials/_footer.php';
    ?>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>

</html>